stages:
- stage: Test
  displayName: Test
  dependsOn:
  - ChangeDetection
  - Build
  variables:
    CodeChanges: $[ stageDependencies.ChangeDetection.Detect.outputs['setvar.CodeChanges'] ]
  jobs:
  - job: RunTests
    displayName: Run unit tests
    pool:
      vmImage: ubuntu-latest
    condition: eq(variables['CodeChanges'], 'true')
    steps:
    - checkout: self

    - task: UseDotNet@2
      displayName: Use .NET SDK
      inputs:
        packageType: sdk
        version: <dotNetSdkVersion>
        includePreviewVersions: <includePreviewVersions>

    - task: DotNetCoreCLI@2
      displayName: Restore test packages
      inputs:
        command: restore
        projects: $(testProjectPath)

    - task: DotNetCoreCLI@2
      displayName: Run tests
      inputs:
        command: test
        projects: $(testProjectPath)
        arguments: --configuration $(buildConfiguration) --no-restore --verbosity normal
