stages:
- stage: Build
  displayName: Build
  dependsOn: ChangeDetection
  variables:
    CodeChanges: $[ stageDependencies.ChangeDetection.Detect.outputs['setvar.CodeChanges'] ]
  jobs:
  - job: BuildSolution
    displayName: Restore, build, and pack
    pool:
      vmImage: ubuntu-latest
    condition: eq(variables['CodeChanges'], 'true')
    steps:
    - checkout: self

    - task: UseDotNet@2
      displayName: Use .NET SDK
      inputs:
        packageType: sdk
        version: 10.0.x
        includePreviewVersions: true

    - task: DotNetCoreCLI@2
      displayName: Restore solution
      inputs:
        command: restore
        projects: $(solutionPath)

    - task: DotNetCoreCLI@2
      displayName: Build solution
      inputs:
        command: build
        projects: $(solutionPath)
        arguments: --configuration $(buildConfiguration) --no-restore

    - task: DotNetCoreCLI@2
      displayName: Pack ValidationEngine.Models
      inputs:
        command: pack
        packagesToPack: $(packableProject1)
        configuration: $(buildConfiguration)
        outputDir: $(packageOutputPath)
        nobuild: false

    - task: DotNetCoreCLI@2
      displayName: Pack ValidationEngine.Reporting
      inputs:
        command: pack
        packagesToPack: $(packableProject2)
        configuration: $(buildConfiguration)
        outputDir: $(packageOutputPath)
        nobuild: false

    - task: DotNetCoreCLI@2
      displayName: Pack ValidationEngine.Analyzers
      inputs:
        command: pack
        packagesToPack: $(packableProject3)
        configuration: $(buildConfiguration)
        outputDir: $(packageOutputPath)
        nobuild: false

    - task: PublishPipelineArtifact@1
      displayName: Publish package artifact
      inputs:
        targetPath: $(packageOutputPath)
        artifactName: $(buildPackageArtifactName)
