trigger:
  branches:
    include:
      - main

pr: none

name: $(Date:yyyyMMdd)$(Rev:.r)

variables:
- template: ../Variables/variables.yml

stages:
- template: change-detection.yml
  parameters:
    mode: main
- template: publish.yml
- template: publish-nuget-org.yml
