trigger: none

pr:
  branches:
    include:
      - main

schedules:
- cron: "<scheduledCronExpression>"
  displayName: Scheduled Main pipeline at <scheduledDisplayTime>
  branches:
    include:
      - main
  always: false

name: $(Date:yyyyMMdd)$(Rev:.r)

variables:
- template: ../Variables/Variables.yml

stages:
- template: ../Shared/ChangeDetection.yml
  parameters:
    mode: main
    codeChangesDetectedMessage: 'Code changes detected. An artifact is expected in staging.'
- template: Swap.yml
- template: Validate.yml
- template: Rollback.yml
