stages:
- stage: Publish
  displayName: Publish
  dependsOn: ChangeDetection
  variables:
    CodeChanges: $[ stageDependencies.ChangeDetection.Detect.outputs['setvar.CodeChanges'] ]
  condition: eq(variables['CodeChanges'], 'true')
  jobs:
  - job: PublishPackage
    displayName: Publish NuGet package
    pool:
      vmImage: ubuntu-latest
    steps:
    - checkout: self

    - task: UseDotNet@2
      displayName: Use .NET SDK
      inputs:
        packageType: sdk
        version: <dotNetSdkVersion>
        includePreviewVersions: <includePreviewVersions>

    - task: DotNetCoreCLI@2
      displayName: Restore packages
      inputs:
        command: restore
        projects: $(projectPath)

    - task: DotNetCoreCLI@2
      displayName: Pack NuGet package
      inputs:
        command: pack
        packagesToPack: $(projectPath)
        configuration: $(buildConfiguration)
        outputDir: $(packageOutputPath)

    - task: NuGetAuthenticate@1
      displayName: Authenticate to Azure Artifacts

    - task: DotNetCoreCLI@2
      displayName: Publish package to Azure Artifacts
      inputs:
        command: custom
        custom: nuget
        arguments: push "$(packageOutputPath)/*.nupkg" --source "$(artifactsFeedUrl)" --api-key AzureDevOps --skip-duplicate
