parameters:
- name: stageName
  type: string
  default: Build
- name: dependsOn
  type: object
  default:
  - ChangeDetection
- name: condition
  type: string
  default: >-
    and(
      not(failed()),
      not(canceled()),
      eq(dependencies.ChangeDetection.outputs['Detect.setvar.CodeChanges'], 'true')
    )

stages:
- stage: ${{ parameters.stageName }}
  displayName: ${{ parameters.stageName }}
  dependsOn: ${{ parameters.dependsOn }}
  condition: ${{ parameters.condition }}
  jobs:
  - job: BuildApplication
    displayName: Restore and build
    pool:
      vmImage: windows-latest
    steps:
    - checkout: self

    - task: UseDotNet@2
      displayName: Use .NET SDK
      inputs:
        packageType: sdk
        version: $(dotNetSdkVersion)
        includePreviewVersions: $(includePreviewVersions)

    - task: DotNetCoreCLI@2
      displayName: Restore packages
      inputs:
        command: restore
        projects: $(solutionPath)

    - task: DotNetCoreCLI@2
      displayName: Build application
      inputs:
        command: build
        projects: $(solutionPath)
        arguments: --configuration $(buildConfiguration) --no-restore

    - task: DotNetCoreCLI@2
      displayName: Publish application
      inputs:
        command: publish
        publishWebProjects: false
        projects: $(appProjectPath)
        arguments: --configuration $(buildConfiguration) --no-build --output $(publishOutputPath)
        zipAfterPublish: true

    - task: PublishPipelineArtifact@1
      displayName: Publish application artifact
      inputs:
        targetPath: $(publishOutputPath)
        artifactName: $(pipelineArtifactName)

    - task: CopyFiles@2
      displayName: Stage build output for tests
      inputs:
        sourceFolder: $(Build.SourcesDirectory)
        contents: '**/bin/$(buildConfiguration)/**'
        targetFolder: $(buildOutputPath)

    - task: PublishPipelineArtifact@1
      displayName: Publish build output artifact
      inputs:
        targetPath: $(buildOutputPath)
        artifactName: $(buildOutputArtifactName)
