trigger: none

pr:
  branches:
    include:
      - dev

name: $(Date:yyyyMMdd)$(Rev:.r)

resources:
  repositories:
  - repository: GlobalStandards
    type: git
    name: GlobalStandards/GlobalStandards
    ref: dev

variables:
- template: ../Variables/Variables.yml

stages:
- template: ../Shared/ChangeDetection.yml
  parameters:
    codeChangesDetectedMessage: 'Code changes detected. Build and test will run.'
- template: ../Shared/StandardsValidation.yml
- template: Build.yml
  parameters:
    dependsOn:
    - ChangeDetection
    - StandardsValidation
- template: Test.yml
- template: Publish.yml
